# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scaleC <- function(X) {
    .Call(`_scPAS_scaleC`, X)
}

OmegaC <- function(Omega, sgn) {
    .Call(`_scPAS_OmegaC`, Omega, sgn)
}

OmegaSC <- function(OmegaS, sgn) {
    .Call(`_scPAS_OmegaSC`, OmegaS, sgn)
}

maxLambdaLmC <- function(X, y, alpha, wbeta, N0, p) {
    .Call(`_scPAS_maxLambdaLmC`, X, y, alpha, wbeta, N0, p)
}

cvTrimLmC <- function(beta, nn, nn2, loco, X, y, N, p, XF, yF, NF) {
    .Call(`_scPAS_cvTrimLmC`, beta, nn, nn2, loco, X, y, N, p, XF, yF, NF)
}

cvHardLmC <- function(beta, betaSTD, cut, wbeta, X, y, N, p, XF, yF, NF) {
    .Call(`_scPAS_cvHardLmC`, beta, betaSTD, cut, wbeta, X, y, N, p, XF, yF, NF)
}

EnetLmC <- function(X, y, alpha, lambda, nlambda, ilambda, wbeta, wbeta2, p, N0, thresh, maxit, thresh2) {
    .Call(`_scPAS_EnetLmC`, X, y, alpha, lambda, nlambda, ilambda, wbeta, wbeta2, p, N0, thresh, maxit, thresh2)
}

cvEnetLmC <- function(X, y, alpha, lambda, nlambda, wbeta, wbeta2, N, p, thresh, maxit, XF, yF, NF, thresh2) {
    .Call(`_scPAS_cvEnetLmC`, X, y, alpha, lambda, nlambda, wbeta, wbeta2, N, p, thresh, maxit, XF, yF, NF, thresh2)
}

NetLmC <- function(X, y, alpha, lambda, nlambda, ilambda, wbeta, wbeta2, Omega, loc, nadj, p, N0, thresh, maxit, thresh2) {
    .Call(`_scPAS_NetLmC`, X, y, alpha, lambda, nlambda, ilambda, wbeta, wbeta2, Omega, loc, nadj, p, N0, thresh, maxit, thresh2)
}

cvNetLmC <- function(X, y, alpha, lambda, nlambda, wbeta, wbeta2, Omega, loc, nadj, N, p, thresh, maxit, XF, yF, NF, thresh2) {
    .Call(`_scPAS_cvNetLmC`, X, y, alpha, lambda, nlambda, wbeta, wbeta2, Omega, loc, nadj, N, p, thresh, maxit, XF, yF, NF, thresh2)
}

maxLambdaCoxC <- function(X, tevent, N, nevent, nevent1, loc1, n, alpha, wbeta, N0, p) {
    .Call(`_scPAS_maxLambdaCoxC`, X, tevent, N, nevent, nevent1, loc1, n, alpha, wbeta, N0, p)
}

pletaCm <- function(xb, exb, nevent, nevent1, loc1, n, ifast, itwo) {
    .Call(`_scPAS_pletaCm`, xb, exb, nevent, nevent1, loc1, n, ifast, itwo)
}

cvTrimCoxC <- function(beta, nn, nn2, loco, XF, NF, neventF, nevent1F, loc1F, nF, X, N, nevent, nevent1, loc1, n, ifast, itwo) {
    .Call(`_scPAS_cvTrimCoxC`, beta, nn, nn2, loco, XF, NF, neventF, nevent1F, loc1F, nF, X, N, nevent, nevent1, loc1, n, ifast, itwo)
}

cvHardCoxC <- function(beta, betaSTD, cut, wbeta, p, XF, NF, neventF, nevent1F, loc1F, nF, X, N, nevent, nevent1, loc1, n, ifast, itwo) {
    .Call(`_scPAS_cvHardCoxC`, beta, betaSTD, cut, wbeta, p, XF, NF, neventF, nevent1F, loc1F, nF, X, N, nevent, nevent1, loc1, n, ifast, itwo)
}

EnetCoxC <- function(X, tevent, alpha, lambda, nlambda, ilambda, wbeta, wbeta2, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast) {
    .Call(`_scPAS_EnetCoxC`, X, tevent, alpha, lambda, nlambda, ilambda, wbeta, wbeta2, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast)
}

cvEnetCoxC <- function(X, tevent, alpha, lambda, nlambda, wbeta, wbeta2, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF) {
    .Call(`_scPAS_cvEnetCoxC`, X, tevent, alpha, lambda, nlambda, wbeta, wbeta2, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF)
}

NetCoxC <- function(X, tevent, alpha, lambda, nlambda, ilambda, wbeta, wbeta2, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast) {
    .Call(`_scPAS_NetCoxC`, X, tevent, alpha, lambda, nlambda, ilambda, wbeta, wbeta2, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast)
}

cvNetCoxC <- function(X, tevent, alpha, lambda, nlambda, wbeta, wbeta2, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF) {
    .Call(`_scPAS_cvNetCoxC`, X, tevent, alpha, lambda, nlambda, wbeta, wbeta2, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF)
}

maxLambdaLogC <- function(X, Z, alpha, wbeta, N0, p) {
    .Call(`_scPAS_maxLambdaLogC`, X, Z, alpha, wbeta, N0, p)
}

cvTrimLogC <- function(beta, nn, nn2, loco, X, y, N, XF, yF, NF, thresh, maxit, threshP) {
    .Call(`_scPAS_cvTrimLogC`, beta, nn, nn2, loco, X, y, N, XF, yF, NF, thresh, maxit, threshP)
}

cvHardLogC <- function(beta, betaSTD, cut, wbeta, X, y, N, p, XF, yF, NF, thresh, maxit, threshP) {
    .Call(`_scPAS_cvHardLogC`, beta, betaSTD, cut, wbeta, X, y, N, p, XF, yF, NF, thresh, maxit, threshP)
}

EnetLogC <- function(X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, p, N0, thresh, maxit, threshP) {
    .Call(`_scPAS_EnetLogC`, X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, p, N0, thresh, maxit, threshP)
}

cvEnetLogC <- function(X, y, alpha, lambda, nlambda, wbeta, wbetai, p, N0, thresh, maxit, XF, yF, NF, threshP) {
    .Call(`_scPAS_cvEnetLogC`, X, y, alpha, lambda, nlambda, wbeta, wbetai, p, N0, thresh, maxit, XF, yF, NF, threshP)
}

NetLogC <- function(X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, threshP) {
    .Call(`_scPAS_NetLogC`, X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, threshP)
}

cvNetLogC <- function(X, y, alpha, lambda, nlambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, XF, yF, NF, threshP) {
    .Call(`_scPAS_cvNetLogC`, X, y, alpha, lambda, nlambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, XF, yF, NF, threshP)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_scPAS_RcppExport_registerCCallable`)
})
